/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.cstaMain;


/**
 *
 * @author punz1738
 */
public class cstaQuiz extends javax.swing.JFrame {
    
public int score;
    /**
     * Creates new form cstaQuiz
     */
    public cstaQuiz() {
        initComponents();
        this.setSize(893,600);
        jButton1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelQ1 = new javax.swing.JPanel();
        Q1 = new javax.swing.JLabel();
        opt1Q1 = new javax.swing.JCheckBox();
        opt3Q1 = new javax.swing.JCheckBox();
        opt4Q1 = new javax.swing.JCheckBox();
        panelQ3 = new javax.swing.JPanel();
        Q3 = new javax.swing.JLabel();
        opt1Q3 = new javax.swing.JCheckBox();
        opt2Q3 = new javax.swing.JCheckBox();
        opt3Q3 = new javax.swing.JCheckBox();
        opt4Q3 = new javax.swing.JCheckBox();
        panelQ4 = new javax.swing.JPanel();
        Q4 = new javax.swing.JLabel();
        opt1Q4 = new javax.swing.JCheckBox();
        opt2Q4 = new javax.swing.JCheckBox();
        opt3Q4 = new javax.swing.JCheckBox();
        opt4Q4 = new javax.swing.JCheckBox();
        panelQ5 = new javax.swing.JPanel();
        Q5 = new javax.swing.JLabel();
        opt1Q5 = new javax.swing.JCheckBox();
        opt2Q5 = new javax.swing.JCheckBox();
        opt3Q5 = new javax.swing.JCheckBox();
        opt4Q5 = new javax.swing.JCheckBox();
        panelQ6 = new javax.swing.JPanel();
        Q6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        panelQ7 = new javax.swing.JPanel();
        Q7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        panelQ8 = new javax.swing.JPanel();
        Q8 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        panelQ9 = new javax.swing.JPanel();
        Q9 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quiz");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        panelQ1.setBackground(new java.awt.Color(50, 50, 50));

        Q1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setText("What types of pollution do computers cause?");

        opt1Q1.setForeground(new java.awt.Color(255, 255, 255));
        opt1Q1.setText("Air");
        opt1Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1Q1ActionPerformed(evt);
            }
        });

        opt3Q1.setForeground(new java.awt.Color(255, 255, 255));
        opt3Q1.setText("Water");
        opt3Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3Q1ActionPerformed(evt);
            }
        });

        opt4Q1.setForeground(new java.awt.Color(255, 255, 255));
        opt4Q1.setText("All of the above");
        opt4Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4Q1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ1Layout = new javax.swing.GroupLayout(panelQ1);
        panelQ1.setLayout(panelQ1Layout);
        panelQ1Layout.setHorizontalGroup(
            panelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q1)
                    .addGroup(panelQ1Layout.createSequentialGroup()
                        .addComponent(opt1Q1)
                        .addGap(73, 73, 73)
                        .addComponent(opt3Q1))
                    .addComponent(opt4Q1))
                .addContainerGap())
        );
        panelQ1Layout.setVerticalGroup(
            panelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1Q1)
                    .addComponent(opt3Q1))
                .addGap(18, 18, 18)
                .addComponent(opt4Q1)
                .addContainerGap())
        );

        panelQ3.setBackground(new java.awt.Color(50, 50, 50));

        Q3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q3.setForeground(new java.awt.Color(255, 255, 255));
        Q3.setText("How many phones are produced daily?");

        opt1Q3.setForeground(new java.awt.Color(255, 255, 255));
        opt1Q3.setText("500,000");
        opt1Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1Q3ActionPerformed(evt);
            }
        });

        opt2Q3.setForeground(new java.awt.Color(255, 255, 255));
        opt2Q3.setText("680,000");
        opt2Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2Q3ActionPerformed(evt);
            }
        });

        opt3Q3.setForeground(new java.awt.Color(255, 255, 255));
        opt3Q3.setText("20,000");
        opt3Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3Q3ActionPerformed(evt);
            }
        });

        opt4Q3.setForeground(new java.awt.Color(255, 255, 255));
        opt4Q3.setText("150,000");
        opt4Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4Q3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ3Layout = new javax.swing.GroupLayout(panelQ3);
        panelQ3.setLayout(panelQ3Layout);
        panelQ3Layout.setHorizontalGroup(
            panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q3)
                    .addGroup(panelQ3Layout.createSequentialGroup()
                        .addGroup(panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt1Q3)
                            .addComponent(opt2Q3))
                        .addGap(44, 44, 44)
                        .addGroup(panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt4Q3)
                            .addComponent(opt3Q3))))
                .addContainerGap())
        );
        panelQ3Layout.setVerticalGroup(
            panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1Q3)
                    .addComponent(opt3Q3))
                .addGap(18, 18, 18)
                .addGroup(panelQ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt2Q3)
                    .addComponent(opt4Q3))
                .addContainerGap())
        );

        panelQ4.setBackground(new java.awt.Color(50, 50, 50));

        Q4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q4.setForeground(new java.awt.Color(255, 255, 255));
        Q4.setText("One bad effect on human health?");

        opt1Q4.setForeground(new java.awt.Color(255, 255, 255));
        opt1Q4.setText("Lack of sleep");
        opt1Q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1Q4ActionPerformed(evt);
            }
        });

        opt2Q4.setForeground(new java.awt.Color(255, 255, 255));
        opt2Q4.setText("Free food");
        opt2Q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2Q4ActionPerformed(evt);
            }
        });

        opt3Q4.setForeground(new java.awt.Color(255, 255, 255));
        opt3Q4.setText("More Money");
        opt3Q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3Q4ActionPerformed(evt);
            }
        });

        opt4Q4.setForeground(new java.awt.Color(255, 255, 255));
        opt4Q4.setText("More work");
        opt4Q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4Q4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ4Layout = new javax.swing.GroupLayout(panelQ4);
        panelQ4.setLayout(panelQ4Layout);
        panelQ4Layout.setHorizontalGroup(
            panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q4)
                    .addGroup(panelQ4Layout.createSequentialGroup()
                        .addGroup(panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt1Q4)
                            .addComponent(opt2Q4))
                        .addGap(18, 18, 18)
                        .addGroup(panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt4Q4)
                            .addComponent(opt3Q4))))
                .addContainerGap())
        );
        panelQ4Layout.setVerticalGroup(
            panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1Q4)
                    .addComponent(opt3Q4))
                .addGap(18, 18, 18)
                .addGroup(panelQ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt2Q4)
                    .addComponent(opt4Q4))
                .addContainerGap())
        );

        panelQ5.setBackground(new java.awt.Color(50, 50, 50));

        Q5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q5.setForeground(new java.awt.Color(255, 255, 255));
        Q5.setText("How is Ottawa reducing pollution?");

        opt1Q5.setForeground(new java.awt.Color(255, 255, 255));
        opt1Q5.setText("Burning fuel");
        opt1Q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1Q5ActionPerformed(evt);
            }
        });

        opt2Q5.setForeground(new java.awt.Color(255, 255, 255));
        opt2Q5.setText("Traffic Light data");
        opt2Q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2Q5ActionPerformed(evt);
            }
        });

        opt3Q5.setForeground(new java.awt.Color(255, 255, 255));
        opt3Q5.setText("Build Roads");
        opt3Q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3Q5ActionPerformed(evt);
            }
        });

        opt4Q5.setForeground(new java.awt.Color(255, 255, 255));
        opt4Q5.setText("Destroy Buildings");
        opt4Q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4Q5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ5Layout = new javax.swing.GroupLayout(panelQ5);
        panelQ5.setLayout(panelQ5Layout);
        panelQ5Layout.setHorizontalGroup(
            panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q5)
                    .addGroup(panelQ5Layout.createSequentialGroup()
                        .addGroup(panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt2Q5)
                            .addComponent(opt1Q5))
                        .addGap(18, 18, 18)
                        .addGroup(panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt3Q5)
                            .addComponent(opt4Q5))))
                .addContainerGap())
        );
        panelQ5Layout.setVerticalGroup(
            panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1Q5)
                    .addComponent(opt3Q5))
                .addGap(18, 18, 18)
                .addGroup(panelQ5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt2Q5)
                    .addComponent(opt4Q5))
                .addContainerGap())
        );

        panelQ6.setBackground(new java.awt.Color(50, 50, 50));

        Q6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q6.setForeground(new java.awt.Color(255, 255, 255));
        Q6.setText("How many tonnes of e-waste are sent to developing countries?");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ6Layout = new javax.swing.GroupLayout(panelQ6);
        panelQ6.setLayout(panelQ6Layout);
        panelQ6Layout.setHorizontalGroup(
            panelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(Q6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        panelQ6Layout.setVerticalGroup(
            panelQ6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelQ7.setBackground(new java.awt.Color(50, 50, 50));

        Q7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q7.setForeground(new java.awt.Color(255, 255, 255));
        Q7.setText("Young people get 6.5 to 7.5 hours of sleep");

        jToggleButton1.setText("True");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("False");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ7Layout = new javax.swing.GroupLayout(panelQ7);
        panelQ7.setLayout(panelQ7Layout);
        panelQ7Layout.setHorizontalGroup(
            panelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q7)
                    .addGroup(panelQ7Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelQ7Layout.setVerticalGroup(
            panelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ7Layout.createSequentialGroup()
                .addComponent(Q7)
                .addGap(18, 18, 18)
                .addGroup(panelQ7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelQ8.setBackground(new java.awt.Color(50, 50, 50));

        Q8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q8.setForeground(new java.awt.Color(255, 255, 255));
        Q8.setText("Do you believe the good out weighs the bad?");

        jToggleButton3.setText("Yes");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setText("No");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQ8Layout = new javax.swing.GroupLayout(panelQ8);
        panelQ8.setLayout(panelQ8Layout);
        panelQ8Layout.setHorizontalGroup(
            panelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q8)
                    .addGroup(panelQ8Layout.createSequentialGroup()
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton4)))
                .addGap(164, 164, 164))
        );
        panelQ8Layout.setVerticalGroup(
            panelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q8)
                .addGap(18, 18, 18)
                .addGroup(panelQ8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelQ9.setBackground(new java.awt.Color(50, 50, 50));

        Q9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Q9.setForeground(new java.awt.Color(255, 255, 255));
        Q9.setText("Rate This Quiz");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("10");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0");

        javax.swing.GroupLayout panelQ9Layout = new javax.swing.GroupLayout(panelQ9);
        panelQ9.setLayout(panelQ9Layout);
        panelQ9Layout.setHorizontalGroup(
            panelQ9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelQ9Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        panelQ9Layout.setVerticalGroup(
            panelQ9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQ9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Q9)
                .addGap(18, 18, 18)
                .addGroup(panelQ9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelQ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelQ9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(1, 1, 1))
                            .addComponent(panelQ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelQ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelQ6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelQ7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(panelQ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelQ9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 893, 574);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel4.setText("Score:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("j");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel6.setText("/6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (opt4Q1.isSelected()){
        score++;
        }
        if (opt1Q3.isSelected()){
        score++;
        }
        if (opt1Q4.isSelected()){
        score++;
        }
        if (opt2Q5.isSelected()){
        score++;
        }
        if (jTextField1.getText().equals("750000") || jTextField1.getText().equals("750,000")){
        score++;
        }
        if (jToggleButton1.isSelected()){
        score++;
        }
        
        jPanel1.setVisible(false);
        jButton1.setVisible(true);
        jLabel5.setText(String.valueOf(score));
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void opt1Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1Q1ActionPerformed
        
        if (opt1Q1.isSelected()){
            
            opt3Q1.setEnabled(false);
            opt4Q1.setEnabled(false);
        }
        else {
            
            opt3Q1.setEnabled(true);
            opt1Q1.setEnabled(true);
            opt4Q1.setEnabled(true);
        }
    }//GEN-LAST:event_opt1Q1ActionPerformed

    private void opt1Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1Q3ActionPerformed
        if (opt1Q3.isSelected()){
            opt2Q3.setEnabled(false);
            opt3Q3.setEnabled(false);
            opt4Q3.setEnabled(false);
        }
        else {
            opt2Q3.setEnabled(true);
            opt3Q3.setEnabled(true);
            opt1Q3.setEnabled(true);
            opt4Q3.setEnabled(true);
        }
    }//GEN-LAST:event_opt1Q3ActionPerformed

    private void opt1Q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1Q4ActionPerformed
        if (opt1Q4.isSelected()){
            opt2Q4.setEnabled(false);
            opt3Q4.setEnabled(false);
            opt4Q4.setEnabled(false);
        }
        else {
            opt2Q4.setEnabled(true);
            opt3Q4.setEnabled(true);
            opt1Q4.setEnabled(true);
            opt4Q4.setEnabled(true);
        }
    }//GEN-LAST:event_opt1Q4ActionPerformed

    private void opt1Q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1Q5ActionPerformed
        if (opt1Q5.isSelected()){
            opt2Q5.setEnabled(false);
            opt3Q5.setEnabled(false);
            opt4Q5.setEnabled(false);
        }
        else {
            opt2Q5.setEnabled(true);
            opt3Q5.setEnabled(true);
            opt1Q5.setEnabled(true);
            opt4Q5.setEnabled(true);
        }
    }//GEN-LAST:event_opt1Q5ActionPerformed

    private void opt3Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3Q1ActionPerformed
        if (opt3Q1.isSelected()){
            
            opt1Q1.setEnabled(false);
            opt4Q1.setEnabled(false);
        }
        else {
            
            opt3Q1.setEnabled(true);
            opt1Q1.setEnabled(true);
            opt4Q1.setEnabled(true);
        }
    }//GEN-LAST:event_opt3Q1ActionPerformed

    private void opt4Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4Q1ActionPerformed
        if (opt4Q1.isSelected()){
            
            opt3Q1.setEnabled(false);
            opt1Q1.setEnabled(false);
        }
        else {
            
            opt3Q1.setEnabled(true);
            opt1Q1.setEnabled(true);
            opt4Q1.setEnabled(true);
        }
    }//GEN-LAST:event_opt4Q1ActionPerformed

    private void opt2Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2Q3ActionPerformed
        if (opt2Q3.isSelected()){
            opt1Q3.setEnabled(false);
            opt3Q3.setEnabled(false);
            opt4Q3.setEnabled(false);
        }
        else {
            opt2Q3.setEnabled(true);
            opt3Q3.setEnabled(true);
            opt1Q3.setEnabled(true);
            opt4Q3.setEnabled(true);
        }
    }//GEN-LAST:event_opt2Q3ActionPerformed

    private void opt3Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3Q3ActionPerformed
        if (opt3Q3.isSelected()){
            opt2Q3.setEnabled(false);
            opt1Q3.setEnabled(false);
            opt4Q3.setEnabled(false);
        }
        else {
            opt2Q3.setEnabled(true);
            opt3Q3.setEnabled(true);
            opt1Q3.setEnabled(true);
            opt4Q3.setEnabled(true);
        }
    }//GEN-LAST:event_opt3Q3ActionPerformed

    private void opt4Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4Q3ActionPerformed
        if (opt4Q3.isSelected()){
            opt2Q3.setEnabled(false);
            opt3Q3.setEnabled(false);
            opt1Q3.setEnabled(false);
        }
        else {
            opt2Q3.setEnabled(true);
            opt3Q3.setEnabled(true);
            opt1Q3.setEnabled(true);
            opt4Q3.setEnabled(true);
        }
    }//GEN-LAST:event_opt4Q3ActionPerformed

    private void opt2Q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2Q4ActionPerformed
        if (opt2Q4.isSelected()){
            opt1Q4.setEnabled(false);
            opt3Q4.setEnabled(false);
            opt4Q4.setEnabled(false);
        }
        else {
            opt2Q4.setEnabled(true);
            opt3Q4.setEnabled(true);
            opt1Q4.setEnabled(true);
            opt4Q4.setEnabled(true);
        }
    }//GEN-LAST:event_opt2Q4ActionPerformed

    private void opt3Q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3Q4ActionPerformed
        if (opt3Q4.isSelected()){
            opt2Q4.setEnabled(false);
            opt1Q4.setEnabled(false);
            opt4Q4.setEnabled(false);
        }
        else {
            opt2Q4.setEnabled(true);
            opt3Q4.setEnabled(true);
            opt1Q4.setEnabled(true);
            opt4Q4.setEnabled(true);
        }
    }//GEN-LAST:event_opt3Q4ActionPerformed

    private void opt4Q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4Q4ActionPerformed
        if (opt4Q4.isSelected()){
            opt2Q4.setEnabled(false);
            opt3Q4.setEnabled(false);
            opt1Q4.setEnabled(false);
        }
        else {
            opt2Q4.setEnabled(true);
            opt3Q4.setEnabled(true);
            opt1Q4.setEnabled(true);
            opt4Q4.setEnabled(true);
        }
    }//GEN-LAST:event_opt4Q4ActionPerformed

    private void opt2Q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2Q5ActionPerformed
        if (opt2Q5.isSelected()){
            opt1Q5.setEnabled(false);
            opt3Q5.setEnabled(false);
            opt4Q5.setEnabled(false);
        }
        else {
            opt2Q5.setEnabled(true);
            opt3Q5.setEnabled(true);
            opt1Q5.setEnabled(true);
            opt4Q5.setEnabled(true);
        }
    }//GEN-LAST:event_opt2Q5ActionPerformed

    private void opt3Q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3Q5ActionPerformed
        if (opt3Q5.isSelected()){
            opt2Q5.setEnabled(false);
            opt1Q5.setEnabled(false);
            opt4Q5.setEnabled(false);
        }
        else {
            opt2Q5.setEnabled(true);
            opt3Q5.setEnabled(true);
            opt1Q5.setEnabled(true);
            opt4Q5.setEnabled(true);
        }
    }//GEN-LAST:event_opt3Q5ActionPerformed

    private void opt4Q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4Q5ActionPerformed
        if (opt4Q5.isSelected()){
            opt2Q5.setEnabled(false);
            opt3Q5.setEnabled(false);
            opt1Q5.setEnabled(false);
        }
        else {
            opt2Q5.setEnabled(true);
            opt3Q5.setEnabled(true);
            opt1Q5.setEnabled(true);
            opt4Q5.setEnabled(true);
        }
    }//GEN-LAST:event_opt4Q5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()){
            jToggleButton2.setEnabled(false);
        }
        else {
            jToggleButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (jToggleButton2.isSelected()){
            jToggleButton1.setEnabled(false);
        }
        else {
            jToggleButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
   
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cstaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cstaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cstaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cstaQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cstaQuiz().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel Q6;
    private javax.swing.JLabel Q7;
    private javax.swing.JLabel Q8;
    private javax.swing.JLabel Q9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JCheckBox opt1Q1;
    private javax.swing.JCheckBox opt1Q3;
    private javax.swing.JCheckBox opt1Q4;
    private javax.swing.JCheckBox opt1Q5;
    private javax.swing.JCheckBox opt2Q3;
    private javax.swing.JCheckBox opt2Q4;
    private javax.swing.JCheckBox opt2Q5;
    private javax.swing.JCheckBox opt3Q1;
    private javax.swing.JCheckBox opt3Q3;
    private javax.swing.JCheckBox opt3Q4;
    private javax.swing.JCheckBox opt3Q5;
    private javax.swing.JCheckBox opt4Q1;
    private javax.swing.JCheckBox opt4Q3;
    private javax.swing.JCheckBox opt4Q4;
    private javax.swing.JCheckBox opt4Q5;
    private javax.swing.JPanel panelQ1;
    private javax.swing.JPanel panelQ3;
    private javax.swing.JPanel panelQ4;
    private javax.swing.JPanel panelQ5;
    private javax.swing.JPanel panelQ6;
    private javax.swing.JPanel panelQ7;
    private javax.swing.JPanel panelQ8;
    private javax.swing.JPanel panelQ9;
    // End of variables declaration//GEN-END:variables
}
