/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CSTA2Quiz;

import my.cstaMain.cstaMain;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        cstaMain.main(args);
    }
}
